# Generated by Django 4.0.3 on 2022-03-11 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardsapp', '0002_alter_deck_flashcard_alter_flashcard_flashcard_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='flashcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcard', to='flashcardsapp.flashcard'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='flashcard_deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_deck', to='flashcardsapp.deck'),
        ),
    ]
