# Generated by Django 4.0.3 on 2022-03-12 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardsapp', '0003_alter_deck_flashcard_alter_flashcard_flashcard_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='deck_user',
            field=models.ForeignKey(db_column='deck_user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deck_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
