# Generated by Django 4.0.3 on 2022-03-17 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardsapp', '0009_flashcard_card_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='flashcard',
        ),
    ]
