# Generated by Django 4.0.3 on 2022-03-17 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardsapp', '0011_alter_deck_deck_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='deck_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deck_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
